// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ServiceLocator.tt
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using IIoc=WPAppStudio.Ioc.Interfaces;
using Ioc=WPAppStudio.Ioc;
using IViewModels=WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.Services
{
    /// <summary>
    /// Implementation of the ViewModel locator service based on IoC.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class ViewModelLocatorService
    {
        // IoC container
        private readonly IIoc.IContainer _container;

        /// <summary>
        /// Initializes a new instance of the <see cref="ViewModelLocatorService" /> class.
        /// </summary>
        public ViewModelLocatorService()
        {
            _container = new Ioc.Container();
        }

        /// <summary>
        /// Gets the reference to a AllNews_NewsViewModel.
        /// </summary>
		public IViewModels.IAllNews_NewsViewModel AllNews_NewsViewModel
        {
            get { return _container.Resolve<IViewModels.IAllNews_NewsViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Media_DetailViewModel.
        /// </summary>
		public IViewModels.IMedia_DetailViewModel Media_DetailViewModel
        {
            get { return _container.Resolve<IViewModels.IMedia_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Health_DetailViewModel.
        /// </summary>
		public IViewModels.IHealth_DetailViewModel Health_DetailViewModel
        {
            get { return _container.Resolve<IViewModels.IHealth_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Entertainment_DetailViewModel.
        /// </summary>
		public IViewModels.IEntertainment_DetailViewModel Entertainment_DetailViewModel
        {
            get { return _container.Resolve<IViewModels.IEntertainment_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Celebrities_EntertainmentViewModel.
        /// </summary>
		public IViewModels.ICelebrities_EntertainmentViewModel Celebrities_EntertainmentViewModel
        {
            get { return _container.Resolve<IViewModels.ICelebrities_EntertainmentViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Business_DetailViewModel.
        /// </summary>
		public IViewModels.IBusiness_DetailViewModel Business_DetailViewModel
        {
            get { return _container.Resolve<IViewModels.IBusiness_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a AllNews_DetailViewModel.
        /// </summary>
		public IViewModels.IAllNews_DetailViewModel AllNews_DetailViewModel
        {
            get { return _container.Resolve<IViewModels.IAllNews_DetailViewModel>(); }
        }
		/// <summary>
        /// Gets the reference to a AboutViewModel.
        /// </summary>
		public IViewModels.IAboutViewModel AboutViewModel
        {
            get { return _container.Resolve<IViewModels.IAboutViewModel>(); }
        }
		
		/// <summary>
        /// Gets the reference to a LicenseViewModel.
        /// </summary>
		public IViewModels.ILicenseViewModel LicenseViewModel
        {
            get { return _container.Resolve<IViewModels.ILicenseViewModel>(); }
        }
    }
}
