// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// AllNews_News ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IAllNews_NewsViewModel
    {		
        /// <summary>
        /// Gets/Sets the AllNews_NewsListControlCollection property.
        /// </summary>
		ObservableCollection<EntitiesBase.RssSearchResult> AllNews_NewsListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedAllNews_NewsListControlCollection property.
        /// </summary>
		EntitiesBase.RssSearchResult SelectedAllNews_NewsListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Business_NewsListControlCollection property.
        /// </summary>
		ObservableCollection<EntitiesBase.RssSearchResult> Business_NewsListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedBusiness_NewsListControlCollection property.
        /// </summary>
		EntitiesBase.RssSearchResult SelectedBusiness_NewsListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Celebrities_NewsListControlCollection property.
        /// </summary>
		ObservableCollection<EntitiesBase.RssSearchResult> Celebrities_NewsListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedCelebrities_NewsListControlCollection property.
        /// </summary>
		EntitiesBase.RssSearchResult SelectedCelebrities_NewsListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Entertainment_NewsListControlCollection property.
        /// </summary>
		ObservableCollection<EntitiesBase.RssSearchResult> Entertainment_NewsListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedEntertainment_NewsListControlCollection property.
        /// </summary>
		EntitiesBase.RssSearchResult SelectedEntertainment_NewsListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Health_NewsListControlCollection property.
        /// </summary>
		ObservableCollection<EntitiesBase.RssSearchResult> Health_NewsListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedHealth_NewsListControlCollection property.
        /// </summary>
		EntitiesBase.RssSearchResult SelectedHealth_NewsListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Media_NewsListControlCollection property.
        /// </summary>
		ObservableCollection<EntitiesBase.RssSearchResult> Media_NewsListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the SelectedMedia_NewsListControlCollection property.
        /// </summary>
		EntitiesBase.RssSearchResult SelectedMedia_NewsListControlCollection { get; set; }
        
        /// <summary>
        /// Gets the RefreshAllNews_NewsListControlCollection command.
        /// </summary>
		ICommand RefreshAllNews_NewsListControlCollection { get; }

        
        /// <summary>
        /// Gets the RefreshBusiness_NewsListControlCollection command.
        /// </summary>
		ICommand RefreshBusiness_NewsListControlCollection { get; }

        
        /// <summary>
        /// Gets the RefreshCelebrities_NewsListControlCollection command.
        /// </summary>
		ICommand RefreshCelebrities_NewsListControlCollection { get; }

        
        /// <summary>
        /// Gets the RefreshEntertainment_NewsListControlCollection command.
        /// </summary>
		ICommand RefreshEntertainment_NewsListControlCollection { get; }

        
        /// <summary>
        /// Gets the RefreshHealth_NewsListControlCollection command.
        /// </summary>
		ICommand RefreshHealth_NewsListControlCollection { get; }

        
        /// <summary>
        /// Gets the RefreshMedia_NewsListControlCollection command.
        /// </summary>
		ICommand RefreshMedia_NewsListControlCollection { get; }

        
        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
		ICommand SetLockScreenCommand { get; }

        
        /// <summary>
        /// Gets the AboutCommand command.
        /// </summary>
		ICommand AboutCommand { get; }

	}
}
