// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// AllNews_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IAllNews_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechAllNews_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechAllNews_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareAllNews_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareAllNews_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartAllNews_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartAllNews_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceAllNews_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceAllNews_DetailStaticControlCommand { get; }

	}
}
