// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Business_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IBusiness_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechBusiness_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechBusiness_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareBusiness_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareBusiness_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartBusiness_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartBusiness_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceBusiness_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceBusiness_DetailStaticControlCommand { get; }

	}
}
