// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Celebrities_Entertainment ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface ICelebrities_EntertainmentViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechEntertainmentStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechEntertainmentStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareEntertainmentStaticControlCommand command.
        /// </summary>
		ICommand ShareEntertainmentStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartEntertainmentStaticControlCommand command.
        /// </summary>
		ICommand PinToStartEntertainmentStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceEntertainmentStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceEntertainmentStaticControlCommand { get; }

	}
}
