// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Media_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IMedia_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechMedia_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechMedia_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareMedia_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareMedia_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartMedia_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartMedia_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceMedia_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceMedia_DetailStaticControlCommand { get; }

	}
}
