// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   UnityContainer.tt
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using IIoc=WPAppStudio.Ioc.Interfaces;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Microsoft.Practices.Unity;
using Repositories=WPAppStudio.Repositories;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using Services=WPAppStudio.Services;
using ViewModels=WPAppStudio.ViewModel;

namespace WPAppStudio.Ioc
{
    //
    // Unity 2.1
    // http://msdn.microsoft.com/en-us/library/hh237493.aspx
    //
    // patterns & practices - Unity
    // http://unity.codeplex.com/
    //
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class Container : IIoc.IContainer
    {
        private readonly IUnityContainer _currentContainer;

        public Container()
        {
            _currentContainer = new UnityContainer();

            _currentContainer.RegisterType<IServices.ILiveTileService, Services.LiveTileService>();
			_currentContainer.RegisterType<IServices.ILockScreenService, Services.LockScreenService>();
            _currentContainer.RegisterType<IServices.IDialogService, Services.DialogService>();
            _currentContainer.RegisterType<IServices.IReminderService, Services.ReminderService>();
            _currentContainer.RegisterType<IServices.IShareService, Services.ShareService>();
            _currentContainer.RegisterType<IServices.ISpeechService, Services.SpeechService>();
            _currentContainer.RegisterType<IServices.INavigationService, Services.NavigationService>();
			_currentContainer.RegisterType<RepositoriesBase.IXmlDataSource, RepositoriesBase.XmlDataSource>();
            _currentContainer.RegisterType<IViewModels.IAllNews_NewsViewModel, ViewModels.AllNews_NewsViewModel>();
            _currentContainer.RegisterType<IViewModels.IMedia_DetailViewModel, ViewModels.Media_DetailViewModel>();
            _currentContainer.RegisterType<IViewModels.IHealth_DetailViewModel, ViewModels.Health_DetailViewModel>();
            _currentContainer.RegisterType<IViewModels.IEntertainment_DetailViewModel, ViewModels.Entertainment_DetailViewModel>();
            _currentContainer.RegisterType<IViewModels.ICelebrities_EntertainmentViewModel, ViewModels.Celebrities_EntertainmentViewModel>();
            _currentContainer.RegisterType<IViewModels.IBusiness_DetailViewModel, ViewModels.Business_DetailViewModel>();
            _currentContainer.RegisterType<IViewModels.IAllNews_DetailViewModel, ViewModels.AllNews_DetailViewModel>();

			_currentContainer.RegisterType<IViewModels.IAboutViewModel, ViewModels.AboutViewModel>(new ContainerControlledLifetimeManager());
			_currentContainer.RegisterType<IViewModels.ILicenseViewModel, ViewModels.LicenseViewModel>(new ContainerControlledLifetimeManager());
			
			if (!System.ComponentModel.DesignerProperties.IsInDesignTool)
            {
				_currentContainer.RegisterType<Repositories.IAllNews_RSS, Repositories.AllNews_RSS>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.IBusiness_YahooBusiness, Repositories.Business_YahooBusiness>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.ICelebrities_CelebritiesRSS, Repositories.Celebrities_CelebritiesRSS>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.IEntertainment_EntertainmentRSS, Repositories.Entertainment_EntertainmentRSS>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.IHealth_HealthRSS, Repositories.Health_HealthRSS>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.IMedia_MediaRSS, Repositories.Media_MediaRSS>(new ContainerControlledLifetimeManager());
			}
			else
			{
				_currentContainer.RegisterType<Repositories.IAllNews_RSS, Repositories.FakeAllNews_RSS>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.IBusiness_YahooBusiness, Repositories.FakeBusiness_YahooBusiness>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.ICelebrities_CelebritiesRSS, Repositories.FakeCelebrities_CelebritiesRSS>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.IEntertainment_EntertainmentRSS, Repositories.FakeEntertainment_EntertainmentRSS>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.IHealth_HealthRSS, Repositories.FakeHealth_HealthRSS>(new ContainerControlledLifetimeManager());
				_currentContainer.RegisterType<Repositories.IMedia_MediaRSS, Repositories.FakeMedia_MediaRSS>(new ContainerControlledLifetimeManager());
			
			}
        }

        public T Resolve<T>()
        {
            return _currentContainer.Resolve<T>();
        }
    }
}
