// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   AboutViewModel.tt
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Entities.Base;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of About ViewModel.
    /// </summary>
    public partial class AboutViewModel : BindableBase, IAboutViewModel
    {       
		private string _title;
		private string _description;
		private string _version;
		private readonly INavigationService _navigationService;
		
		public string Title 
		{ 
			get 
			{ 
				return _title; 
			} 
			set
			{
				SetProperty(ref _title, value);
			}			
		}
		
		public string Description 
		{ 
			get 
			{ 
				return _description; 
			} 
			set
			{
				SetProperty(ref _description, value);
			}			
		}

		public string Version 
		{ 
			get 
			{ 
				return _version; 
			} 
			set
			{
				SetProperty(ref _version, value);
			}			
		}
				
        /// <summary>
        /// Initializes a new instance of the <see cref="AboutViewModel" /> class.
        /// </summary>
        public AboutViewModel(INavigationService navigationService)
        {
			_title = @"Yahoo News";
			_description = @"Your news, your way!!"; 
			_version =  "v1"; 
			_navigationService = navigationService;
        }
		
		private ICommand _licenseCommand;

        /// <summary>
        /// Gets the LicenseCommand command.
        /// </summary>
        public ICommand LicenseCommand
        {
            get { return _licenseCommand = _licenseCommand ?? new DelegateCommand(LicenseCommandDelegate); }
        }

        public void LicenseCommandDelegate()
        {
            _navigationService.NavigateTo<ILicenseViewModel>();
        }
    }
}
