// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using Controls=WPAppStudio.Controls;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Localization=WPAppStudio.Localization;
using Repositories=WPAppStudio.Repositories;
using Services=WPAppStudio.Services;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Business_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class Business_DetailViewModel : EntitiesBase.BindableBase, IViewModels.IBusiness_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Business_DetailViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public Business_DetailViewModel(IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
		private EntitiesBase.RssSearchResult _currentRssSearchResult;

        /// <summary>
        /// CurrentRssSearchResult property.
        /// </summary>		
        public EntitiesBase.RssSearchResult CurrentRssSearchResult
        {
            get
            {
				return _currentRssSearchResult;
            }
            set
            {
                SetProperty(ref _currentRssSearchResult, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechBusiness_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechBusiness_DetailStaticControlCommandDelegate() 
        {
	
				_speechService.TextToSpeech(CurrentRssSearchResult.Title + " " + CurrentRssSearchResult.Content);
        }
		

        private ICommand _textToSpeechBusiness_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechBusiness_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechBusiness_DetailStaticControlCommand
        {
            get { return _textToSpeechBusiness_DetailStaticControlCommand = _textToSpeechBusiness_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechBusiness_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareBusiness_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareBusiness_DetailStaticControlCommandDelegate() 
        {
	
				_shareService.Share(CurrentRssSearchResult.Title,CurrentRssSearchResult.Summary, CurrentRssSearchResult.FeedUrl);
        }
		

        private ICommand _shareBusiness_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareBusiness_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareBusiness_DetailStaticControlCommand
        {
            get { return _shareBusiness_DetailStaticControlCommand = _shareBusiness_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(ShareBusiness_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartBusiness_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartBusiness_DetailStaticControlCommandDelegate() 
        {
	
				_liveTileService.PinToStart(typeof(IViewModels.IBusiness_DetailViewModel), CreateTileInfoBusiness_DetailStaticControl());
        }
		

        private ICommand _pinToStartBusiness_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartBusiness_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartBusiness_DetailStaticControlCommand
        {
            get { return _pinToStartBusiness_DetailStaticControlCommand = _pinToStartBusiness_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartBusiness_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourceBusiness_DetailStaticControlCommand command.
        /// </summary>
        public  void GoToSourceBusiness_DetailStaticControlCommandDelegate() 
        {
	
				_navigationService.NavigateTo(string.IsNullOrEmpty(CurrentRssSearchResult.FeedUrl) ? null : new Uri(CurrentRssSearchResult.FeedUrl));
        }
		

        private ICommand _goToSourceBusiness_DetailStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourceBusiness_DetailStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourceBusiness_DetailStaticControlCommand
        {
            get { return _goToSourceBusiness_DetailStaticControlCommand = _goToSourceBusiness_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(GoToSourceBusiness_DetailStaticControlCommandDelegate); }
        }
		public object NavigationContext
        {
            set
            {              
                if (!(value is EntitiesBase.RssSearchResult)) { return; }
                
                CurrentRssSearchResult = value as EntitiesBase.RssSearchResult;
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the Business_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfoBusiness_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentRssSearchResult.Title,
                Title = CurrentRssSearchResult.Title,
                BackTitle = CurrentRssSearchResult.Title,
                BackContent = CurrentRssSearchResult.Content,
                Count = 0,
                BackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                BackBackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                LogoPath = "DoWApp-Logo.png"
            };
            return tileInfo;
        }
    }
}
