// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using Controls=WPAppStudio.Controls;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Localization=WPAppStudio.Localization;
using Repositories=WPAppStudio.Repositories;
using Services=WPAppStudio.Services;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Celebrities_Entertainment ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class Celebrities_EntertainmentViewModel : EntitiesBase.BindableBase, IViewModels.ICelebrities_EntertainmentViewModel, ViewModelsBase.INavigable
    {       

		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Celebrities_EntertainmentViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public Celebrities_EntertainmentViewModel(IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
		private EntitiesBase.RssSearchResult _currentRssSearchResult;

        /// <summary>
        /// CurrentRssSearchResult property.
        /// </summary>		
        public EntitiesBase.RssSearchResult CurrentRssSearchResult
        {
            get
            {
				return _currentRssSearchResult;
            }
            set
            {
                SetProperty(ref _currentRssSearchResult, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechEntertainmentStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechEntertainmentStaticControlCommandDelegate() 
        {
	
				_speechService.TextToSpeech(CurrentRssSearchResult.Title + " " + CurrentRssSearchResult.Content);
        }
		

        private ICommand _textToSpeechEntertainmentStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechEntertainmentStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechEntertainmentStaticControlCommand
        {
            get { return _textToSpeechEntertainmentStaticControlCommand = _textToSpeechEntertainmentStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechEntertainmentStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareEntertainmentStaticControlCommand command.
        /// </summary>
        public  void ShareEntertainmentStaticControlCommandDelegate() 
        {
	
				_shareService.Share(CurrentRssSearchResult.Title,CurrentRssSearchResult.Summary, CurrentRssSearchResult.FeedUrl);
        }
		

        private ICommand _shareEntertainmentStaticControlCommand;

        /// <summary>
        /// Gets the ShareEntertainmentStaticControlCommand command.
        /// </summary>
        public ICommand ShareEntertainmentStaticControlCommand
        {
            get { return _shareEntertainmentStaticControlCommand = _shareEntertainmentStaticControlCommand ?? new ViewModelsBase.DelegateCommand(ShareEntertainmentStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartEntertainmentStaticControlCommand command.
        /// </summary>
        public  void PinToStartEntertainmentStaticControlCommandDelegate() 
        {
	
				_liveTileService.PinToStart(typeof(IViewModels.ICelebrities_EntertainmentViewModel), CreateTileInfoEntertainmentStaticControl());
        }
		

        private ICommand _pinToStartEntertainmentStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartEntertainmentStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartEntertainmentStaticControlCommand
        {
            get { return _pinToStartEntertainmentStaticControlCommand = _pinToStartEntertainmentStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartEntertainmentStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourceEntertainmentStaticControlCommand command.
        /// </summary>
        public  void GoToSourceEntertainmentStaticControlCommandDelegate() 
        {
	
				_navigationService.NavigateTo(string.IsNullOrEmpty(CurrentRssSearchResult.FeedUrl) ? null : new Uri(CurrentRssSearchResult.FeedUrl));
        }
		

        private ICommand _goToSourceEntertainmentStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourceEntertainmentStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourceEntertainmentStaticControlCommand
        {
            get { return _goToSourceEntertainmentStaticControlCommand = _goToSourceEntertainmentStaticControlCommand ?? new ViewModelsBase.DelegateCommand(GoToSourceEntertainmentStaticControlCommandDelegate); }
        }
		public object NavigationContext
        {
            set
            {              
                if (!(value is EntitiesBase.RssSearchResult)) { return; }
                
                CurrentRssSearchResult = value as EntitiesBase.RssSearchResult;
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the EntertainmentStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfoEntertainmentStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentRssSearchResult.Title,
                Title = CurrentRssSearchResult.Title,
                BackTitle = CurrentRssSearchResult.Title,
                BackContent = CurrentRssSearchResult.Content,
                Count = 0,
                BackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                BackBackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                LogoPath = "DoWApp-Logo.png"
            };
            return tileInfo;
        }
    }
}
