// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using Controls=WPAppStudio.Controls;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Localization=WPAppStudio.Localization;
using Repositories=WPAppStudio.Repositories;
using Services=WPAppStudio.Services;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Health_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class Health_DetailViewModel : EntitiesBase.BindableBase, IViewModels.IHealth_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Health_DetailViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public Health_DetailViewModel(IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
		private EntitiesBase.RssSearchResult _currentRssSearchResult;

        /// <summary>
        /// CurrentRssSearchResult property.
        /// </summary>		
        public EntitiesBase.RssSearchResult CurrentRssSearchResult
        {
            get
            {
				return _currentRssSearchResult;
            }
            set
            {
                SetProperty(ref _currentRssSearchResult, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechHealth_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechHealth_DetailStaticControlCommandDelegate() 
        {
	
				_speechService.TextToSpeech(CurrentRssSearchResult.Title + " " + CurrentRssSearchResult.Content);
        }
		

        private ICommand _textToSpeechHealth_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechHealth_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechHealth_DetailStaticControlCommand
        {
            get { return _textToSpeechHealth_DetailStaticControlCommand = _textToSpeechHealth_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechHealth_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareHealth_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareHealth_DetailStaticControlCommandDelegate() 
        {
	
				_shareService.Share(CurrentRssSearchResult.Title,CurrentRssSearchResult.Summary, CurrentRssSearchResult.FeedUrl);
        }
		

        private ICommand _shareHealth_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareHealth_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareHealth_DetailStaticControlCommand
        {
            get { return _shareHealth_DetailStaticControlCommand = _shareHealth_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(ShareHealth_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartHealth_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartHealth_DetailStaticControlCommandDelegate() 
        {
	
				_liveTileService.PinToStart(typeof(IViewModels.IHealth_DetailViewModel), CreateTileInfoHealth_DetailStaticControl());
        }
		

        private ICommand _pinToStartHealth_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartHealth_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartHealth_DetailStaticControlCommand
        {
            get { return _pinToStartHealth_DetailStaticControlCommand = _pinToStartHealth_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartHealth_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourceHealth_DetailStaticControlCommand command.
        /// </summary>
        public  void GoToSourceHealth_DetailStaticControlCommandDelegate() 
        {
	
				_navigationService.NavigateTo(string.IsNullOrEmpty(CurrentRssSearchResult.FeedUrl) ? null : new Uri(CurrentRssSearchResult.FeedUrl));
        }
		

        private ICommand _goToSourceHealth_DetailStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourceHealth_DetailStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourceHealth_DetailStaticControlCommand
        {
            get { return _goToSourceHealth_DetailStaticControlCommand = _goToSourceHealth_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(GoToSourceHealth_DetailStaticControlCommandDelegate); }
        }
		public object NavigationContext
        {
            set
            {              
                if (!(value is EntitiesBase.RssSearchResult)) { return; }
                
                CurrentRssSearchResult = value as EntitiesBase.RssSearchResult;
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the Health_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfoHealth_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentRssSearchResult.Title,
                Title = CurrentRssSearchResult.Title,
                BackTitle = CurrentRssSearchResult.Title,
                BackContent = CurrentRssSearchResult.Content,
                Count = 0,
                BackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                BackBackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                LogoPath = "DoWApp-Logo.png"
            };
            return tileInfo;
        }
    }
}
