// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows.Input;
using Controls=WPAppStudio.Controls;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Localization=WPAppStudio.Localization;
using Repositories=WPAppStudio.Repositories;
using Services=WPAppStudio.Services;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Media_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class Media_DetailViewModel : EntitiesBase.BindableBase, IViewModels.IMedia_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Media_DetailViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public Media_DetailViewModel(IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
		private EntitiesBase.RssSearchResult _currentRssSearchResult;

        /// <summary>
        /// CurrentRssSearchResult property.
        /// </summary>		
        public EntitiesBase.RssSearchResult CurrentRssSearchResult
        {
            get
            {
				return _currentRssSearchResult;
            }
            set
            {
                SetProperty(ref _currentRssSearchResult, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechMedia_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechMedia_DetailStaticControlCommandDelegate() 
        {
	
				_speechService.TextToSpeech(CurrentRssSearchResult.Title + " " + CurrentRssSearchResult.Content);
        }
		

        private ICommand _textToSpeechMedia_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechMedia_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechMedia_DetailStaticControlCommand
        {
            get { return _textToSpeechMedia_DetailStaticControlCommand = _textToSpeechMedia_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechMedia_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareMedia_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareMedia_DetailStaticControlCommandDelegate() 
        {
	
				_shareService.Share(CurrentRssSearchResult.Title,CurrentRssSearchResult.Summary, CurrentRssSearchResult.FeedUrl);
        }
		

        private ICommand _shareMedia_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareMedia_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareMedia_DetailStaticControlCommand
        {
            get { return _shareMedia_DetailStaticControlCommand = _shareMedia_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(ShareMedia_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartMedia_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartMedia_DetailStaticControlCommandDelegate() 
        {
	
				_liveTileService.PinToStart(typeof(IViewModels.IMedia_DetailViewModel), CreateTileInfoMedia_DetailStaticControl());
        }
		

        private ICommand _pinToStartMedia_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartMedia_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartMedia_DetailStaticControlCommand
        {
            get { return _pinToStartMedia_DetailStaticControlCommand = _pinToStartMedia_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartMedia_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourceMedia_DetailStaticControlCommand command.
        /// </summary>
        public  void GoToSourceMedia_DetailStaticControlCommandDelegate() 
        {
	
				_navigationService.NavigateTo(string.IsNullOrEmpty(CurrentRssSearchResult.FeedUrl) ? null : new Uri(CurrentRssSearchResult.FeedUrl));
        }
		

        private ICommand _goToSourceMedia_DetailStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourceMedia_DetailStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourceMedia_DetailStaticControlCommand
        {
            get { return _goToSourceMedia_DetailStaticControlCommand = _goToSourceMedia_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(GoToSourceMedia_DetailStaticControlCommandDelegate); }
        }
		public object NavigationContext
        {
            set
            {              
                if (!(value is EntitiesBase.RssSearchResult)) { return; }
                
                CurrentRssSearchResult = value as EntitiesBase.RssSearchResult;
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the Media_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfoMedia_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentRssSearchResult.Title,
                Title = CurrentRssSearchResult.Title,
                BackTitle = CurrentRssSearchResult.Title,
                BackContent = CurrentRssSearchResult.Content,
                Count = 0,
                BackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                BackBackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                LogoPath = "DoWApp-Logo.png"
            };
            return tileInfo;
        }
    }
}
